### ISSUE TITLE
Any progress

### ISSUE THREAD

**Issue by duanyu** [eminorhan/relational-recurrent#1]
Happy to see your  implementation of relational recurrent network :)

Have you got any progress in it recently ? 
I mean have you found why your implementation got worse results than original LSTM ?

**Comment by duanyu** [comment]
I find that in your code, you use "sigmoid" for recurrent_activation, but in original keras LSTM's implementation the recurrent_activation is "hard_sigmoid", in addition, you use "he_normal" for recurrent_initializer, but original implementation use "orthogonal".

I'm not sure whether these differences bring your worse results here, but you can try it :)

**Comment by eminorhan** [comment]
OK, thank you for pointing that out! I will try that when I get a chance. The current code doesn't do worse than the LSTM, it's about the same as the LSTM. I haven't worked on this recently, but I was thinking that perhaps I just hadn't trained the model long enough.
